version: "3.8"
services:
  api:
      build: ./api
      container_name: api
      command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; uvicorn main:app --host 0.0.0.0 --port 8000'
      depends_on:
        - postgres
      ports:
          - 8000:8000
      env_file:
        - .env
  bot:
      build: ./bot
      container_name: bot
      command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; python bot.py'
      depends_on:
        - postgres
      expose:
        - 8081
      env_file:
        - .env
  web:
      stdin_open: true
      build: ./frontend
      restart: always
      container_name: web
      ports:
        - 80:80
        - 443:443
      depends_on:
        - api
  postgres:
      image: postgres:15-alpine
      container_name: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      restart: always
      environment:
        - POSTGRES_USER=$DB_USER
        - POSTGRES_PASSWORD=$DB_PASS
        - POSTGRES_DB=$DB_NAME
      expose:
        - 5432
      ports:
        - 5432:5432
      env_file:
        - .env

volumes:
  postgres_data: